# Generated by Django 2.2.1 on 2020-04-11 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_pic', models.ImageField(default='C:\\PythonCourse\x0cinalproject\x0cinalproject\\handwriting_recognition\\static\\media', upload_to='C:\\PythonCourse\x0cinalproject\x0cinalproject\\handwriting_recognition\\static\\media')),
            ],
        ),
    ]
